---
# --- Docker ---

- name: Install prerequisites
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: true

# --- Install Tailscale ---

- name: Install Tailscale
  ansible.builtin.shell: |
    curl -fsSL https://tailscale.com/install.sh | sh && sudo tailscale up --auth-key={{ vault_tailscale_auth_key }}
  args:
    creates: /var/lib/tailscale/tailscaled.state

# --- Unattended upgrades ---

- name: Install unattended-upgrades
  ansible.builtin.apt:
    name: unattended-upgrades
    state: present

- name: Enable automatic security updates
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    mode: "0644"
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
