apiVersion: v1
stringData:
    auth: ENC[AES256_GCM,data:TmaUlzTK4Zqvsj9d3WF/lqLUG0ukyDdEolyN+uerIX/MneA/QtN5MCRoc10x/DYrSJbDvWmt9r4gHZYWUxI8,iv:ueVJUY+pRntniyTUqwUMAhlG94Omoe85Kq5l2E6GrkM=,tag:MmyjiB0DpBKPpq6a7wkbWQ==,type:str]
kind: Secret
metadata:
    name: basic-auth
    namespace: longhorn-system
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5QytGYStHZFl1bXV6aGxa
            SXN5T2N3NXhoM1NxUStXelZIbDRwMVI3d2tBCm80SVd1WUZvSlRkRXZiVENRcmdP
            NmFlLy95SjFhanRqZ0NicmNJQzgyR3cKLS0tIDRJbFQ5N1hvRXFKakE0M2RnWE5M
            ZUlhNFIrbkZZTWFocTNWQXJRRnpCQTQKgYn4JK5RQa57Ejt83fLpayVTrUXA9gwR
            RV3R0k08KbBlWlguXMCBWCgFDvmTUR58EVX42jDlMcyogo+jDrLV2g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d8weq7fp7wct6sxvve94hap9v6jz6336txft64t5d5rx39vwwunq8nyjys
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-18T23:42:02Z"
    mac: ENC[AES256_GCM,data:gWQw0n2r13z+6xV58ZeKG9VqvW8187Kkw4GXp/fFDueSIsbd0kC5ZFlYGZGUnTKBuO46HUY+g3nGNrtUk+d4YNAm/kagG4SgD4FuZ2FslqBqrjcvCnbydLyJsM4BCN3nYatlsFo1emLemkf0xnKL2CQ6KpEfuUvy8EwMwhIe/s4=,iv:EF9ftW8NfNIjbDUP/WeUneq9g/lORKIj4qNpE0LkhnM=,tag:TY8VxDmXwoN0prC2DRFzOw==,type:str]
    version: 3.13.0
