apiVersion: v1
data:
    auth: ENC[AES256_GCM,data:XYSHRuhPwxGJPTPWE5rlHMVQBewugBvEJ+pSOS7r5YHi9BCyVdJ6U0Xa5L738L+aoG9WVRTzqmCSQXByLt92X0n31p1BLzhrBLjv9+Ah5QudOYsC6BlKxA==,iv:YWRwIoPDMnbL7v79xa/5NIFuGoMrpVON0UtzKdzVxeI=,tag:3wxqJjARt/rsPIhCmZamcA==,type:str]
kind: Secret
metadata:
    creationTimestamp: "2026-05-18T19:08:38Z"
    name: basic-auth
    namespace: longhorn-system
    resourceVersion: "2809398"
    uid: 12c080db-004a-4680-bb04-44fee3cec89d
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5QytGYStHZFl1bXV6aGxa
            SXN5T2N3NXhoM1NxUStXelZIbDRwMVI3d2tBCm80SVd1WUZvSlRkRXZiVENRcmdP
            NmFlLy95SjFhanRqZ0NicmNJQzgyR3cKLS0tIDRJbFQ5N1hvRXFKakE0M2RnWE5M
            ZUlhNFIrbkZZTWFocTNWQXJRRnpCQTQKgYn4JK5RQa57Ejt83fLpayVTrUXA9gwR
            RV3R0k08KbBlWlguXMCBWCgFDvmTUR58EVX42jDlMcyogo+jDrLV2g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d8weq7fp7wct6sxvve94hap9v6jz6336txft64t5d5rx39vwwunq8nyjys
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-18T19:09:35Z"
    mac: ENC[AES256_GCM,data:FrZZxJ6VHCzVsCW7210QnnakIR3qrAqyO34hhxQUVTyuXs4fPlRzDCAu/MOcIf8paF5JGqPLGVVT9IcSuVu9WDktVm+ReElzOXTzyLhExr/O+nf9+szi6x/abA/dhWuUqkkNTZ914GB+9OSwMtweV9ZwZHEENdjHne0wWFP3Joo=,iv:UAdWUmtQxLwmxtbsiAtymKLbSYLhCEjnBexjDhPMn24=,tag:o0kGXv9QEbLu5sy2+g+A5A==,type:str]
    version: 3.13.0
