apiVersion: v1
data:
    auth: ENC[AES256_GCM,data:XYSHRuhPwxGJPTPWE5rlHMVQBewugBvEJ+pSOS7r5YHi9BCyVdJ6U0Xa5L738L+aoG9WVRTzqmCSQXByLt92X0n31p1BLzhrBLjv9+Ah5QudOYsC6BlKxA==,iv:YWRwIoPDMnbL7v79xa/5NIFuGoMrpVON0UtzKdzVxeI=,tag:3wxqJjARt/rsPIhCmZamcA==,type:str]
kind: Secret
metadata:
    name: basic-auth
    namespace: longhorn-system
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5QytGYStHZFl1bXV6aGxa
            SXN5T2N3NXhoM1NxUStXelZIbDRwMVI3d2tBCm80SVd1WUZvSlRkRXZiVENRcmdP
            NmFlLy95SjFhanRqZ0NicmNJQzgyR3cKLS0tIDRJbFQ5N1hvRXFKakE0M2RnWE5M
            ZUlhNFIrbkZZTWFocTNWQXJRRnpCQTQKgYn4JK5RQa57Ejt83fLpayVTrUXA9gwR
            RV3R0k08KbBlWlguXMCBWCgFDvmTUR58EVX42jDlMcyogo+jDrLV2g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d8weq7fp7wct6sxvve94hap9v6jz6336txft64t5d5rx39vwwunq8nyjys
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-18T22:06:23Z"
    mac: ENC[AES256_GCM,data:we5qZ2RN/jQbsTwKETeal5GOsgArsnfeic8GENTkQvLZjkH4q62FYTJiuiXoatfg7NRyegIsQDVjUtxv5yAkBp1bVLDQHi44tbHu6uz2RIGdPAoSn59x1OecQR+XIjnbyw8EOJk8yyrYWCI22Wn+2PLvrEc6ApoFV7S3PhsRw4c=,iv:bAagaA4INgFOX2HXwdRR3W1i1owjo3y777uSCHhZfDQ=,tag:1WvOp/0aSRb8jJQCP/lv7w==,type:str]
    version: 3.13.0
