#!/bin/sh
# Turn "helm install" guides into Flux manifests and raise a PR with the result.
#
# Inputs are plain text files at nefcloud/<dir>/helm holding the helm commands
# a guide tells you to run (comments, blank lines, `\` continuations and
# non-helm lines such as `kubectl get pod` are fine):
#
#   helm repo add tailscale https://pkgs.tailscale.com/helmcharts
#   helm upgrade --install tailscale-release tailscale/tailscale-operator \
#     --namespace tailscale --create-namespace --version 1.96.5 -f values.yaml
#
# For every such file the script (re)writes, next to it:
#   helmrepo.yaml     HelmRepository per repo used (in the release's namespace)
#   helmrelease.yaml  HelmRelease per `helm install|upgrade`
#   namespace.yaml    only for releases passing --create-namespace
# and makes sure they are listed in <dir>/kustomization.yaml (created if
# missing) and <dir> in nefcloud/kustomization.yaml. Existing entries are never
# removed. The generated files are overwritten on every run, so edit the `helm`
# file, not them. The `helm` file is only parsed, never executed.
#
# Supported: repo add (https), install/upgrade with <repo>/<chart>, -n/--namespace,
# --version, -f/--values (a values*.yaml next to the `helm` file, inlined into the
# HelmRelease), --create-namespace; --install/--wait/--atomic are ignored.
# Anything else is an error rather than being silently dropped. That includes a
# helm call behind a path, a common prefix (sudo, env, VAR=x, ...) or an operator
# (`/usr/bin/helm ...`, `sudo helm ...`, `cd x && helm ...`), and shell operators
# or expansions in the commands that are acted on (repo add, install, upgrade).
# The prefix check is a heuristic: wrappers with arguments (`sudo -u root helm`)
# are not recognised. Every other command is skipped: `kubectl ...`,
# `brew install helm`, `export X=$(...)`, and read-only helm ones such as
# `helm list | grep x`. The HelmRelease is named after the release, so keep the
# release name of anything already running (a rename makes Flux uninstall the
# old one and install a new one).
#
# Each HelmRepository, HelmRelease and Namespace may come from one directory
# only (kustomize rejects duplicates): use another repo name for a second
# `helm repo add` of the same URL, and --create-namespace in one directory per
# namespace. Warnings (unpinned chart, a namespace.yaml that is no longer
# generated) go to stderr and into the description of a newly opened PR (an
# already open PR keeps its description).
#
# Changes go to the fixed branch $PR_BRANCH (force-pushed, bot-owned) and a PR
# into $BASE_BRANCH is opened unless one is already open. Nothing to change
# means no push and no PR. Running it again on its own output is a no-op.
#
# Requires: flux (only for --export, no cluster access needed), git, awk, sed,
# gh (to open the PR; not with DRY_RUN=1 or OPEN_PR=0) and GITHUB_TOKEN
# (contents + pull requests write on the repo).
# Runs on a GitHub-hosted runner (.github/workflows/flux-helm.yml). By hand:
#   GITHUB_TOKEN=... ./flux-helm.sh
#
# Configuration (environment, defaults below):
#   OWNER REPO BASE_BRANCH PR_BRANCH   where to read from and open the PR
#   REPO_URL      any git URL to clone instead of GitHub (e.g. a local path)
#   ROOT          directory scanned for */helm (default nefcloud)
#   REPO_INTERVAL RELEASE_INTERVAL     reconcile intervals of the generated objects
#   FLUX_VERSION  fail unless the flux CLI is exactly this version; the CLI
#                 decides the apiVersions and layout of the generated objects
#   PR_DRAFT=true open the PR as a draft
#   DRY_RUN=1     print the diff and stop; no push, no PR, no token needed with REPO_URL
#   OPEN_PR=0     push the branch but do not call the GitHub API
#
# Conventions: UPPERCASE variables are configuration or per-run state shared
# between functions (CUR_DIR, CUR_FILE, STATE, REG, CMD_OPS); everything else is
# `local`. Wrapped in main() so a truncated file can never run half a script.
# shellcheck shell=dash
set -eu

GEN_HEADER_PREFIX="# Generated by flux-helm.sh"

main() {
  OWNER="${OWNER:-martin-nef}"
  REPO="${REPO:-cluster-infra}"
  BASE_BRANCH="${BASE_BRANCH:-main}"
  PR_BRANCH="${PR_BRANCH:-flux-helm-sync}"
  ROOT="${ROOT:-nefcloud}"
  HELM_FILE=helm
  REPO_INTERVAL="${REPO_INTERVAL:-12h}"
  RELEASE_INTERVAL="${RELEASE_INTERVAL:-10m}"
  FLUX_VERSION="${FLUX_VERSION:-}"
  PR_DRAFT="${PR_DRAFT:-false}"
  DRY_RUN="${DRY_RUN:-0}"
  OPEN_PR="${OPEN_PR:-1}"
  check_config

  if [ -z "${REPO_URL:-}" ]; then
    : "${GITHUB_TOKEN:?GITHUB_TOKEN must be set}"
    REPO_URL="https://x-access-token:$GITHUB_TOKEN@github.com/$OWNER/$REPO.git"
  fi
  if [ "$DRY_RUN" != 1 ] && [ "$OPEN_PR" = 1 ]; then
    : "${GITHUB_TOKEN:?GITHUB_TOKEN must be set}"
  fi

  WORKDIR="$(mktemp -d)"
  # The signal traps exit so the run stops (and reports it) instead of carrying
  # on with its workdir gone; the EXIT trap does the cleanup.
  trap cleanup EXIT
  trap 'exit 129' HUP
  trap 'exit 130' INT
  trap 'exit 143' TERM

  # What each directory generates, to catch the same object coming from two
  # directories. Lines are "<key> <dir>".
  REG="$WORKDIR/reg"
  mkdir "$REG"
  : > "$REG/repos"
  : > "$REG/releases"
  : > "$REG/namespaces"
  : > "$WORKDIR/warnings"

  # Work on a fresh, full clone (open_pr compares against the parent of the
  # sync branch's tip, which a shallow clone may not have) rather than the local
  # checkout, so the same code runs on a runner and by hand.
  local repo_dir="$WORKDIR/clone" found=0 helm
  git clone -q --branch "$BASE_BRANCH" "$REPO_URL" "$repo_dir"
  git -C "$repo_dir" config user.name "Flux Bot"
  git -C "$repo_dir" config user.email "flux@users.noreply.github.com"
  cd "$repo_dir"

  for helm in "$ROOT"/*/"$HELM_FILE"; do
    [ -f "$helm" ] || continue
    found=1
    # Values files are collected as a space-separated list.
    case "$helm" in
      *[[:space:]]*) die "whitespace in a path is not supported: $helm" ;;
    esac
    sync_dir "$(dirname "$helm")"
  done
  [ "$found" = 1 ] || echo "no $ROOT/*/$HELM_FILE files found"

  if [ -z "$(git status --porcelain -- "$ROOT")" ]; then
    echo "manifests up to date"
    return
  fi
  git add -A -- "$ROOT"

  if [ "$DRY_RUN" = 1 ]; then
    git --no-pager diff --cached
    return
  fi
  open_pr
}

die() {
  echo "flux-helm: $*" >&2
  exit 1
}

# Shown on stderr and, when a PR is opened, in its description.
warn() {
  echo "warning: $*" >&2
  echo "$*" >> "$WORKDIR/warnings"
}

cleanup() {
  cd / && rm -rf "$WORKDIR"
}

need() {
  command -v "$1" > /dev/null 2>&1 || die "$1 is required but not installed"
}

valid_name() {
  case "$1" in
    "" | *[!a-z0-9-]* | -* | *-) return 1 ;;
  esac
}

valid_ref() {
  case "$1" in
    "" | -* | *[!A-Za-z0-9._/-]* | *..*) return 1 ;;
  esac
}

check_config() {
  local actual
  need git
  need flux
  if [ "$DRY_RUN" != 1 ] && [ "$OPEN_PR" = 1 ]; then
    need gh
  fi
  valid_ref "$BASE_BRANCH" || die "invalid BASE_BRANCH: $BASE_BRANCH"
  valid_ref "$PR_BRANCH" || die "invalid PR_BRANCH: $PR_BRANCH"
  case "$PR_DRAFT" in
    true | false) ;;
    *) die "PR_DRAFT must be true or false: $PR_DRAFT" ;;
  esac
  actual="$(flux --version)"
  if [ -n "$FLUX_VERSION" ] && [ "${actual##* }" != "$FLUX_VERSION" ]; then
    die "flux $FLUX_VERSION is required, found: $actual"
  fi
  echo "using $actual"
}

# Lex a helm file like a shell would (quotes, backslashes, comments, line
# continuations) without expanding anything. Emits "T<word>" per word, "O<char>"
# per unquoted shell operator character (; & | < > ( )) and "E" at the end of
# each command.
tokenize() {
  awk '
    function flush() {
      if (have) {
        if (index(tok, "\n")) { print "multi-line word not supported" > "/dev/stderr"; exit 1 }
        print "T" tok; ntok++
      }
      tok = ""; have = 0
    }
    {
      sub(/\r$/, "")
      n = length($0); cont = 0
      for (i = 1; i <= n; i++) {
        c = substr($0, i, 1)
        if (q == "\047") { if (c == "\047") q = ""; else tok = tok c; continue }
        if (q == "\"") {
          if (c == "\"") q = ""
          else if (c == "\\" && i == n) cont = 1
          else if (c == "\\") {
            i++; d = substr($0, i, 1)
            if (d == "\"" || d == "\\" || d == "$" || d == "`") tok = tok d; else tok = tok c d
          } else tok = tok c
          continue
        }
        if (c == "\047" || c == "\"") { q = c; have = 1; continue }
        if (c == "\\") {
          if (i == n) cont = 1; else { i++; tok = tok substr($0, i, 1); have = 1 }
          continue
        }
        if (c == " " || c == "\t") { flush(); continue }
        if (index(";&|<>()", c)) {
          flush(); op = c
          while (i < n && index(";&|<>()", substr($0, i + 1, 1))) { i++; op = op substr($0, i, 1) }
          print "O" op; ntok++; continue
        }
        if (c == "#" && !have) break
        tok = tok c; have = 1
      }
      if (q != "") { if (!cont) tok = tok "\n"; next }
      if (cont) next
      flush()
      if (ntok > 0) { print "E"; ntok = 0 }
    }
    END { if (q != "") { print "unterminated quote" > "/dev/stderr"; exit 1 } }
  ' "$1"
}

# Regenerate the manifests for one nefcloud/<dir>/helm. Sets the per-directory
# state the helpers below read: CUR_DIR, CUR_FILE, STATE (scratch files) and
# CMD_OPS (the current command contained shell operators).
sync_dir() {
  local dir="$1" f ns generated="helmrepo.yaml helmrelease.yaml"
  CUR_DIR="$dir"
  CUR_FILE="$dir/$HELM_FILE"
  STATE="$WORKDIR/state"
  echo "$CUR_DIR: reading $CUR_FILE"

  rm -rf "$STATE"
  mkdir -p "$STATE"
  : > "$STATE/repos"      # alias url
  : > "$STATE/releases"   # ns name
  : > "$STATE/namespaces"
  : > "$STATE/helmrepo.yaml"
  : > "$STATE/helmrelease.yaml"

  tokenize "$CUR_FILE" > "$STATE/tokens" || die "$CUR_FILE: cannot parse"

  read_commands

  [ -s "$STATE/releases" ] || die "$CUR_FILE: no helm install/upgrade found"

  if [ -s "$STATE/namespaces" ]; then
    : > "$STATE/namespace.yaml"
    while read -r ns; do
      printf -- '---\napiVersion: v1\nkind: Namespace\nmetadata:\n  name: %s\n' "$ns" >> "$STATE/namespace.yaml"
    done < "$STATE/namespaces"
    generated="namespace.yaml $generated"
  elif [ -f "$dir/namespace.yaml" ] && grep -q "^$GEN_HEADER_PREFIX" "$dir/namespace.yaml"; then
    # Entries are never removed on purpose: dropping a Namespace from the
    # manifests makes Flux prune it together with everything inside.
    warn "$dir/namespace.yaml is no longer generated ($CUR_FILE has no --create-namespace) but it is still there and listed in $dir/kustomization.yaml; delete it and its entry by hand if the Namespace should go (Flux then prunes the Namespace and everything in it)"
  fi

  if [ ! -f "$dir/kustomization.yaml" ]; then
    printf 'apiVersion: kustomize.config.k8s.io/v1beta1\nkind: Kustomization\nresources: []\n' > "$dir/kustomization.yaml"
  fi
  for f in $generated; do
    {
      echo "$GEN_HEADER_PREFIX from ./$HELM_FILE. Do not edit; change ./$HELM_FILE instead."
      cat "$STATE/$f"
    } > "$dir/$f"
    kustomization_add "$dir/kustomization.yaml" "$f"
  done
  kustomization_add "$ROOT/kustomization.yaml" "$(basename "$dir")"
}

# claim <registry> <what> <key> <hint>: record that the current directory
# generates <key>. Returns 1 if it already did; dies if another directory does,
# as kustomize would reject the duplicate object.
claim() {
  local reg="$REG/$1" what="$2" key="$3" hint="$4" owner
  owner="$(awk -v k="$key" '$1 == k { print $2; exit }' "$reg")"
  if [ -z "$owner" ]; then
    echo "$key $CUR_DIR" >> "$reg"
  elif [ "$owner" = "$CUR_DIR" ]; then
    return 1
  else
    die "$CUR_FILE: $what $key is also generated from $owner/$HELM_FILE; $hint"
  fi
}

# Feed the tokenizer's output to handle_command, one command at a time. Also
# notes (CMD_HIDDEN) a helm call that does not start its command plainly, so
# that skipping a line can never drop one: `helm` right after a prefix word or
# an operator, or spelled as a path. A `helm` further in (`brew install helm`,
# `grep helm`) is just an argument. Sets the per-command CMD_OPS, CMD_START and
# CMD_HIDDEN.
read_commands() {
  local line w
  set --
  CMD_OPS=0 CMD_START=1 CMD_HIDDEN=0
  while IFS= read -r line; do
    case "$line" in
      T*)
        w="${line#T}"
        if [ "$CMD_START" = 1 ]; then
          case "$w" in
            sudo | doas | env | time | nice | nohup | command | exec | -* | *=*) ;;
            helm) [ $# -eq 0 ] || CMD_HIDDEN=1; CMD_START=0 ;;
            /*/helm | ./helm | ../*/helm) CMD_HIDDEN=1; CMD_START=0 ;;
            *) CMD_START=0 ;;
          esac
        fi
        set -- "$@" "$w" ;;
      O*) set -- "$@" "${line#O}"; CMD_OPS=1 CMD_START=1 ;;
      E) handle_command "$@"; set --; CMD_OPS=0 CMD_START=1 CMD_HIDDEN=0 ;;
    esac
  done < "$STATE/tokens"
}

# $@: the tokens of a command that is acted on (repo add, install, upgrade).
no_shell_syntax() {
  local t
  [ "$CMD_OPS" = 0 ] || die "$CUR_FILE: shell operators (; & | < > ( )) are not supported in helm repo add/install/upgrade, use one helm command per line (in: $*)"
  for t in "$@"; do
    case "$t" in
      *'$'* | *'`'*) die "$CUR_FILE: shell expansion is not supported (in: $*)" ;;
    esac
  done
}

# $@: one tokenized command line
handle_command() {
  [ "$CMD_HIDDEN" = 0 ] || die "$CUR_FILE: 'helm' must be the first word of its line, written plainly: no path, prefix (sudo, env, VAR=x) or operator (; && |) before it (in: $*); put each helm command on its own line"
  if [ "$1" != helm ]; then
    echo "  skipping (not helm): $*"
    return
  fi
  case "${2:-}:${3:-}" in
    repo:add | install:* | upgrade:*) no_shell_syntax "$@" ;;
  esac
  shift
  case "${1:-}" in
    repo)
      shift
      case "${1:-}" in
        add) shift; helm_repo_add "$@" ;;
        update | list) ;;
        *) die "$CUR_FILE: unsupported command: helm repo $*" ;;
      esac
      ;;
    install | upgrade) shift; helm_release "$@" ;;
    search | show | list | ls | status | get | history | version | template | lint | pull) ;;
    *) die "$CUR_FILE: unsupported command: helm $*" ;;
  esac
}

# $@: <name> <url> [--force-update]
helm_repo_add() {
  local a name="" url=""
  for a in "$@"; do
    case "$a" in
      --force-update) ;;
      -*) die "$CUR_FILE: unsupported flag for helm repo add: $a" ;;
      *) if [ -z "$name" ]; then name="$a"; elif [ -z "$url" ]; then url="$a"; else die "$CUR_FILE: too many arguments to helm repo add"; fi ;;
    esac
  done
  [ -n "$url" ] || die "$CUR_FILE: helm repo add needs <name> <url>"
  valid_name "$name" || die "$CUR_FILE: invalid repo name: $name"
  case "$url" in
    https://* | http://*) ;;
    *) die "$CUR_FILE: only http(s) chart repositories are supported: $url" ;;
  esac
  if grep -q "^$name " "$STATE/repos"; then die "$CUR_FILE: repo $name added twice"; fi
  echo "$name $url" >> "$STATE/repos"
}

# $1: a -f/--values argument
check_values_file() {
  case "$1" in
    values*.yaml) ;;
    *) die "$CUR_FILE: values file must be named values*.yaml next to $HELM_FILE (the workflow only watches those): $1" ;;
  esac
  case "$1" in
    *[!A-Za-z0-9._-]*) die "$CUR_FILE: invalid values file name: $1" ;;
  esac
  [ -f "$CUR_DIR/$1" ] || die "$CUR_FILE: values file not found: $CUR_DIR/$1"
}

# $@: <release> <repo>/<chart> [flags]
helm_release() {
  local name="" chart="" ns=default version="" createns=0 values=""
  local flag val repo chartname url v
  while [ $# -gt 0 ]; do
    case "$1" in
      --namespace=* | --version=* | --values=*)
        flag="${1%%=*}" val="${1#*=}"; shift ;;
      --namespace | -n | --version | --values | -f)
        [ $# -ge 2 ] || die "$CUR_FILE: $1 needs a value"
        flag="$1" val="$2"; shift 2 ;;
      --create-namespace) createns=1; shift; continue ;;
      --install | -i | --wait | --wait-for-jobs | --atomic) shift; continue ;;
      -*) die "$CUR_FILE: unsupported flag: $1" ;;
      *)
        if [ -z "$name" ]; then name="$1"
        elif [ -z "$chart" ]; then chart="$1"
        else die "$CUR_FILE: unexpected argument: $1"; fi
        shift; continue ;;
    esac
    case "$flag" in
      --namespace | -n) ns="$val" ;;
      --version) version="$val" ;;
      --values | -f) check_values_file "$val"; values="$values $CUR_DIR/$val" ;;
    esac
  done
  [ -n "$chart" ] || die "$CUR_FILE: helm install needs <release> <repo>/<chart>"
  valid_name "$name" || die "$CUR_FILE: invalid release name: $name"
  valid_name "$ns" || die "$CUR_FILE: invalid namespace: $ns"

  case "$chart" in
    */*/* | /* | ./* | ../*) die "$CUR_FILE: only <repo>/<chart> references are supported: $chart" ;;
    */*) ;;
    *) die "$CUR_FILE: only <repo>/<chart> references are supported: $chart" ;;
  esac
  repo="${chart%%/*}" chartname="${chart#*/}"
  url="$(sed -n "s/^$repo //p" "$STATE/repos")"
  [ -n "$url" ] || die "$CUR_FILE: no 'helm repo add $repo <url>' before $chart"
  [ -n "$version" ] || warn "$CUR_FILE: release $name has no --version, so the chart floats to the latest release on every reconcile"

  claim releases HelmRelease "$ns/$name" "release names must be unique per namespace" \
    || die "$CUR_FILE: release $name in $ns defined twice"
  echo "$ns $name" >> "$STATE/releases"
  if [ "$createns" = 1 ] && claim namespaces Namespace "$ns" "pass --create-namespace in only one directory per namespace"; then
    echo "$ns" >> "$STATE/namespaces"
  fi
  if claim repos HelmRepository "$ns/$repo" "add the repo under another name in one of them (helm repo add <name> <url>)"; then
    flux create source helm "$repo" --namespace="$ns" --url="$url" \
      --interval="$REPO_INTERVAL" --export >> "$STATE/helmrepo.yaml"
  fi

  set -- "$name" --namespace="$ns" --source="HelmRepository/$repo" --chart="$chartname" \
    --interval="$RELEASE_INTERVAL"
  [ -z "$version" ] || set -- "$@" --chart-version="$version"
  for v in $values; do set -- "$@" --values="$v"; done
  flux create helmrelease "$@" --export >> "$STATE/helmrelease.yaml"
  echo "  $ns/$name: chart $chart${version:+ $version}"
}

# Append "  - <entry>" to the resources: list of a kustomization.yaml unless it is
# already listed (./x and x/ count as x). Never reorders or removes anything. A
# file it cannot edit safely (flow-style list, several resources: keys, ...) is
# an error: appending a second resources: key would silently replace the list.
kustomization_add() {
  local file="$1" entry="$2"
  awk -v entry="$entry" -v file="$file" '
    function norm(s) { sub(/^\.\//, "", s); sub(/\/+$/, "", s); return s }
    function fail(msg) { print file ": " msg > "/dev/stderr"; exit 1 }
    function dump(  i) { for (i = 1; i <= NR; i++) print line[i] }
    { line[NR] = $0 }
    END {
      for (i = 1; i <= NR; i++) {
        l = line[i]
        if (l ~ /^resources:/) {
          if (start) fail("more than one top-level resources: key")
          start = i; inres = 0
          if (l ~ /^resources:[ \t]*(#.*)?$/) inres = 1
          else if (l ~ /^resources:[ \t]*\[[ \t]*\][ \t]*(#.*)?$/) empty = 1
          else fail("resources: must be a block list (\"- item\" lines) or []; rewrite it that way")
          continue
        }
        if (!inres) continue
        if (l ~ /^[ \t]*(#.*)?$/) continue
        if (l ~ /^[ \t]*-[ \t]/) {
          last = i
          v = l; sub(/^[ \t]*-[ \t]+/, "", v); sub(/[ \t]*(#.*)?$/, "", v); gsub(/["\047]/, "", v)
          if (norm(v) == norm(entry)) present = 1
          continue
        }
        if (l ~ /^[^ \t#-]/) { inres = 0; continue }
        fail("unrecognised line in the resources: list: " l)
      }
      if (present) { dump(); exit 0 }
      if (!start) { dump(); print "resources:"; print "  - " entry; exit 0 }
      at = last ? last : start
      indent = "  "
      if (last) { indent = line[last]; sub(/-.*/, "", indent) }
      for (i = 1; i <= NR; i++) {
        if (i == start && empty) { print "resources:"; print indent "- " entry; continue }
        print line[i]
        if (i == at && !empty) print indent "- " entry
      }
    }
  ' "$file" > "$WORKDIR/kustomization.tmp" || die "cannot update $file"
  cat "$WORKDIR/kustomization.tmp" > "$file"
}

# Commit the staged changes to $PR_BRANCH (force-pushed unless it already holds
# exactly this) and open a PR unless one is already open.
open_pr() {
  local title files existing body pr_url
  title="chore(flux): sync helm releases"
  files="$(git diff --cached --name-only)"
  git checkout -q -b "$PR_BRANCH"
  git commit -q -m "$title" -m "Generated by flux-helm.sh from $ROOT/*/$HELM_FILE on $BASE_BRANCH."
  echo "changes:"
  echo "$files" | sed 's/^/  /'

  if git fetch -q origin "$PR_BRANCH" 2> /dev/null && git diff --quiet FETCH_HEAD HEAD \
    && [ "$(git rev-parse FETCH_HEAD^)" = "$(git rev-parse HEAD^)" ]; then
    echo "branch $PR_BRANCH already up to date"
  else
    git push -q -f origin "HEAD:refs/heads/$PR_BRANCH"
    echo "pushed $PR_BRANCH"
  fi
  [ "$OPEN_PR" = 1 ] || return 0

  # gh prints the API's own error message and exits non-zero on any failure,
  # which set -e turns into a failed run (no falling through to the next call).
  existing="$(gh api "repos/$OWNER/$REPO/pulls?state=open&head=$OWNER:$PR_BRANCH" --jq '.[0].html_url // empty')"
  if [ -n "$existing" ]; then
    echo "PR already open: $existing"
    # e.g. a PR stacked on a branch that has since been merged
    gh api -X PATCH "repos/$OWNER/$REPO/pulls/${existing##*/}" -f base="$BASE_BRANCH" --silent \
      || echo "warning: could not set the PR base to $BASE_BRANCH" >&2
    return
  fi

  body="Generated by flux-helm.sh from \`$ROOT/*/$HELM_FILE\`. Edit the helm file on $BASE_BRANCH rather than this branch, it is force-pushed on every run.

Changed files:
$(echo "$files" | sed 's/^/- /')"
  if [ -s "$WORKDIR/warnings" ]; then
    body="$body

Warnings:
$(sed 's/^/- /' "$WORKDIR/warnings")"
  fi
  pr_url="$(gh api -X POST "repos/$OWNER/$REPO/pulls" \
    -f title="$title" -f head="$PR_BRANCH" -f base="$BASE_BRANCH" -f body="$body" \
    -F draft="$PR_DRAFT" --jq .html_url)"
  [ -n "$pr_url" ] || die "failed to open PR for $PR_BRANCH"
  echo "opened PR $pr_url"
}

main "$@"
