apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    tunnel: 55b9993e-5d22-4ec0-b996-2cfa58ebaf33
    credentials-file: /etc/cloudflared/credentials.json

    # Static pass-through: Forward ALL wildcard traffic straight to Traefik
    ingress:
      - service: http://cluster.local
