apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-credentials
    namespace: cloudflared
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:YQVb6ziR7xslxbamRFgtN6OwHBHQJ0dkvHZENE64UCF8GMUp6BmVXu7RxY7nLK1rehJRgxdeKY2ZpXK3Rtg5kJEkdw0xI1WIqNCZgmWSZUP44QaQzL9DCiiiT/z8v8lfVv3JrYXexWgseb07cYvMiPgznr3yioDIlA74zDVztMuVJVpuwQinw0OMmhV7t8JkveAHxTGtZ4jupBtqJbRrn9kNyKg/nDu8BAPwUA==,iv:j9GgWc+g2L/+GKK72CXmXDj7m3mub8CfXe2EDEh9h5g=,tag:ES4g3o+f/vb5lEzZEw2vDQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiM2hJYWZZMlRBSi9NU1FV
            K05DVWxsK1psN0REc1RiRWErYy9hQnhWVHlRCktFTEhIL3BweUhvUVB0T1NTNUFW
            N0ZvY0R1c2VFWS80NkpLM3QrTjR3QlEKLS0tIHNHQ1RmazM1N0l3bk5VM1hOSEFQ
            aWZYanpEQTc5SkU4L3R3SjdRNW5ndjgKNfs+hWAUbEvK/RE5p0ea/UZuD3KWDOU7
            uX0/rfgG+atm0U2TOSGJoHi20vVx9oEh/uz+/VV/6GFod3t7FTzD8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d8weq7fp7wct6sxvve94hap9v6jz6336txft64t5d5rx39vwwunq8nyjys
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-18T22:25:49Z"
    mac: ENC[AES256_GCM,data:t3th+Yr6hLW4OLrEVl0Q6XCQpEih0qa3eOn/vbo8EOfBRFjbTc2Bywfi/oAw7+YQ6kQccBygvKycsFgr2L599RKTrO75cV0P9pzKGd9qz+yvud+h8pahnHbmZYFiQLwomuV7+W4bidL/Iz8D0ditUzopMPk+U7tOx9LICTklu/s=,iv:gT8xGt8JzrpDOsxpjxbWZ5Fi2XAYnFTwBiF+NXX5Eg4=,tag:28hT3F7mbaWrn7JdpgOsnA==,type:str]
    version: 3.13.0
