apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-credentials
    namespace: cloudflared
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:Db52DFbkMGQNPSyeu/IL8pLXZ1ZWleRE/xUE5omzRDA0sPuZri1NatN4fjXUuxIqqqlxWPzrChlX4DgTsOm9upaT71xSrAtGVv7+GH+46qDvbma1KsM9AMNMx82Z5N9Nd884IuVo8a6Z/G25LBmuaIWgB4K6zzROa1tg4YzQZA8wC/cJUDy7m+hQnn3lf/4mRSkOvZfvu8lWKZ+KrxdNAkbi0vtHFaoZWOGZiTw=,iv:NMPYR5U2z7AZ4g0gae872H80CuY24gcWLKKL1Kp/8Z8=,tag:eqAz3Xzpil4ym+R5/md/pw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiM2hJYWZZMlRBSi9NU1FV
            K05DVWxsK1psN0REc1RiRWErYy9hQnhWVHlRCktFTEhIL3BweUhvUVB0T1NTNUFW
            N0ZvY0R1c2VFWS80NkpLM3QrTjR3QlEKLS0tIHNHQ1RmazM1N0l3bk5VM1hOSEFQ
            aWZYanpEQTc5SkU4L3R3SjdRNW5ndjgKNfs+hWAUbEvK/RE5p0ea/UZuD3KWDOU7
            uX0/rfgG+atm0U2TOSGJoHi20vVx9oEh/uz+/VV/6GFod3t7FTzD8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d8weq7fp7wct6sxvve94hap9v6jz6336txft64t5d5rx39vwwunq8nyjys
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-17T19:23:49Z"
    mac: ENC[AES256_GCM,data:iZN/KdSSYtzQzYoMdJ6u2PjEnFboJiwnhWwzBLkBpuvCLB+RHn5dhg5dUtJIY9dCEpG5BEgo05nQEgsFsacq2owz4pCcO8vgChRvYvu2TQmQpUMbYgForxpUabSZypLumN9V+B3IRMQs8pOdgavSalFJTtAxHc0aJXF5PauJIvU=,iv:FQpi2uwKfQknIt1cKIsnjV/RXKdb9ir7/qBt57Tuco8=,tag:p3dFno7LYLYbPGNN1a2Ceg==,type:str]
    version: 3.13.0
