apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    nodeSelector:
      node-role.kubernetes.io/gateway: "true"
    tolerations:
      - key: node-role.kubernetes.io/gateway
        operator: Equal
        value: "true"
        effect: NoSchedule
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
    ports:
      minecraft-rpg:
        port: 25566
        expose:
          default: true
        exposedPort: 25566
        protocol: TCP
      minecraft-vanilla:
        port: 25565
        expose:
          default: true
        exposedPort: 25565
        protocol: TCP
      minecraft-atm:
        port: 25567
        expose:
          default: true
        exposedPort: 25567
        protocol: TCP
      minecraft-create:
        port: 25568
        expose:
          default: true
        exposedPort: 25568
        protocol: TCP
      valheim:
        port: 1001
        expose:
          default: true
        exposedPort: 1001
        protocol: UDP
