apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepo.yaml
  - helmrelease.yaml
  - ingress.yaml
  - rbac.yaml
  - auth-proxy.yaml
configMapGenerator:
  - name: headlamp-auth-nginx
    namespace: kube-system
    files:
      - default.conf.template
