---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: minecraft
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: minecraft-auth
  url: https://github.com/martin-nef/minecraft
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minecraft
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./deploy
  prune: true
  sourceRef:
    kind: GitRepository
    name: minecraft
  decryption:
    provider: sops
    secretRef:
      name: sops-age-minecraft
