---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: smart-reviewer
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: smart-reviewer-auth
  url: ssh://git@github.com/martin-nef/smart-reviewer.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: smart-reviewer
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./deploy
  prune: true
  sourceRef:
    kind: GitRepository
    name: smart-reviewer
