---
k3s_cluster:
  children:
    server:
      hosts:
        shitbox:
          ansible_user: deploy
          tailscale_ip: 100.102.128.57
          tailscale_host: shitbox
        oci-small-1:
          ansible_user: ubuntu
          tailscale_ip: 100.68.249.22
          tailscale_host: oci-small-1
          extra_server_args: >-
            {{ default_server_args }}
            --disable-apiserver
            --disable-controller-manager
            --disable-scheduler
            --node-taint hardware.capacity=low-ram:NoSchedule
        oci-big-1:
          ansible_user: ubuntu
          tailscale_ip: 100.109.118.21
          tailscale_host: oci-big-1
          extra_server_args: >-
            {{ default_server_args }}
            --node-label node-role.kubernetes.io/gateway=true

    agent:
      hosts:
        oci-small-2:
          ansible_user: ubuntu
          tailscale_ip: 100.71.125.10
          tailscale_host: oci-small-2
          extra_agent_args: >-
            {{ default_agent_args }}
            --node-label node-role.kubernetes.io/gateway=true
            --node-taint node-role.kubernetes.io/gateway=true:NoSchedule
    # TODO: set up this node at some point to add GPU capacity
    #     dumb-computer:

  vars:
    k3s_version: v1.36.0+k3s1
    token: "{{ vault_k3s_token }}"   # store in Ansible Vault

    # All inter-node k3s traffic uses Tailscale IPs.
    # The first server in the inventory is the bootstrap node.
    api_endpoint: "{{ hostvars[groups['server'][0]]['tailscale_ip'] }}"

    # Route Flannel node-to-node traffic over Tailscale.
    server_config_yaml: "{{ default_config_yaml }}"
    agent_config_yaml: "{{ default_config_yaml }}"
    default_config_yaml: |
      flannel-iface: tailscale0


    # Every server advertises and binds to its Tailscale IP.
    extra_server_args: "{{ default_server_args }}"
    default_server_args: >-
      --node-ip {{ tailscale_ip }}
      --advertise-address {{ tailscale_ip }}
      --tls-san {{ tailscale_host }}

    # Agents also bind to their Tailscale IP.
    extra_agent_args: "{{ default_agent_args }}"
    default_agent_args: "--node-ip {{ tailscale_ip }}"
