---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: oauth2-proxy-repo
  namespace: oauth2-proxy
spec:
  url: https://oauth2-proxy.github.io/manifests
  interval: 12h0m1s
