---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2-proxy-release
  namespace: oauth2-proxy
spec:
  chart:
    spec:
      chart: oauth2-proxy
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy-repo
      version: ">=10.0.0 <11.0.0"
  interval: 10m0s
  values:
    config:
      existingSecret: google-oauth2-creds
    extraArgs:
      cookie-secure: "true"
      cookie-refresh: "1h"
      cookie-expire: "168h"
      skip-provider-button: "true"
