apiVersion: v1
kind: Secret
metadata:
    name: google-oauth2-creds
    namespace: oauth2-proxy
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:wC6tTj6dKPXU6PiiK3aUmEaHbjsnxyquQdN5uWQ5X+EZ4BTfVsMihQ0orUvRnwvWniAbwTTO1IYlkBQTZWL5Dkhbib+t3kat,iv:5xTMUTthm7MCWfanEaj8vcmjl5FmveV+W+nsRkwv0h0=,tag:87LmUk+TRNO07Mgf5kJWvw==,type:str]
    client-secret: ENC[AES256_GCM,data:HEcuFF5ZZQHdbIN4TjLwsdkB/ybTESS6VBuK0+X+xmT5eOo=,iv:uJHYdThG3y+v/T4v7gIztiAoVKoO2UgVzicOnMGr3DU=,tag:DnQHkwgTQmCqOlQrbpJ6Kw==,type:str]
    cookie-secret: ENC[AES256_GCM,data:Qt/0w4TdNNgfnuL+mIvFIfMbEfJYjxes8vFu+ZpS9vCQCFTHb8IT5QzBO8g=,iv:6OAzPFDpeCb34X6q2tKU97zV/KqhL261qJ18xxsd328=,tag:wy0vmzTR/kWXMpWug5MYdw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQlFWQWVkVE82anNJa01K
            NEV5Q1Z4aVlkNkZmcVBIZE1xbmt5NmF5bldBClBoTjJteHVnQ0JKNEdqQmlRQ0I4
            cUVIOEtpaFZXMnlEZU55T01nTVFrbzQKLS0tIDdEQ1IvbzJXKzBHYnp6dS9pV2Fo
            RjlNV2w5UFJHNkJIYy9ac2tBZ2ZZTXcKGNR+9WMUmD2xvw3PlR6S2IAYN990Bs5w
            wNrmylnUENyR2UMcfT36n6GVQBUnKgfCeYTNR4H1fVvzqam1xOWkbw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d8weq7fp7wct6sxvve94hap9v6jz6336txft64t5d5rx39vwwunq8nyjys
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-17T20:22:20Z"
    mac: ENC[AES256_GCM,data:COPPcVc7cNkwTCkpqHiknSM8v5R/USl1n0ZBZfTMrDNXTiv6rbHhw99fmu4k+qxVWBMzdUdHSOe500tGBGiNXl40G5q7p+iCi37Wyughkz0J26IX08bPI8CU1SZ1QDqAe0rwwwetsXFHGxsMjLuid9ZFZMsDSy6jd+RjnlLh8bc=,iv:a/HXnBkNEk7cQKmPSjIlNCBuIaIe+PIZ11JAbTEGe+Y=,tag:YzhUgGF7KbW5gKFj4cp6Dg==,type:str]
    version: 3.13.0
