apiVersion: v1
kind: Secret
metadata:
    name: google-oauth2-creds
    namespace: oauth2-proxy
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:wC6tTj6dKPXU6PiiK3aUmEaHbjsnxyquQdN5uWQ5X+EZ4BTfVsMihQ0orUvRnwvWniAbwTTO1IYlkBQTZWL5Dkhbib+t3kat,iv:5xTMUTthm7MCWfanEaj8vcmjl5FmveV+W+nsRkwv0h0=,tag:87LmUk+TRNO07Mgf5kJWvw==,type:str]
    client-secret: ENC[AES256_GCM,data:HEcuFF5ZZQHdbIN4TjLwsdkB/ybTESS6VBuK0+X+xmT5eOo=,iv:uJHYdThG3y+v/T4v7gIztiAoVKoO2UgVzicOnMGr3DU=,tag:DnQHkwgTQmCqOlQrbpJ6Kw==,type:str]
    cookie-secret: ENC[AES256_GCM,data:zesVFJkprEKNne5gEnjLtfjVZmX6ss4+45KXuDp5PgLBWpSPMYLGQuHVv/E=,iv:YvmL/8RtIEZSrXQpthaB2ZWomW5rRNPDNFJeMgO4gis=,tag:u5BWxviBiuuGOtFsZuNV9w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQlFWQWVkVE82anNJa01K
            NEV5Q1Z4aVlkNkZmcVBIZE1xbmt5NmF5bldBClBoTjJteHVnQ0JKNEdqQmlRQ0I4
            cUVIOEtpaFZXMnlEZU55T01nTVFrbzQKLS0tIDdEQ1IvbzJXKzBHYnp6dS9pV2Fo
            RjlNV2w5UFJHNkJIYy9ac2tBZ2ZZTXcKGNR+9WMUmD2xvw3PlR6S2IAYN990Bs5w
            wNrmylnUENyR2UMcfT36n6GVQBUnKgfCeYTNR4H1fVvzqam1xOWkbw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d8weq7fp7wct6sxvve94hap9v6jz6336txft64t5d5rx39vwwunq8nyjys
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-17T22:33:33Z"
    mac: ENC[AES256_GCM,data:PfTmZjMvXEkET7y5XLzuq4fnt96IynJ0C39ENe+/7WVVKAk0JThijs8MZFDtDPEuM8od/5z77rl7sc9zWo4RaBg49eb3ADP8LyFfxazwb2rTFXfT9FTSM2gs64SHbaD04cIEdQrlT/JqrQUGad0WR0RKVGBiTjjutRxEVX88JUQ=,iv:yLrG9OjkJF0/zlxF3LkJH3EemRwxdvvXq8eNwh5ThA0=,tag:LAdIoaMTlWIPyJQFT/gVvQ==,type:str]
    version: 3.13.0
