config:
  existingSecret: google-oauth2-creds
  provider: google
  cookieDomain: .nefcloud.top
authenticatedEmailsFile:
  enabled: true
  persistence: configmap
  template: admin-emails
  restrictedUserAccessKey: allowed_emails.txt
extraArgs:
  cookie-secure: "true"
  cookie-refresh: "1h"
  cookie-expire: "168h"
  cookie-samesite: "lax"
  cookie-csrf-per-request: "true"
  skip-provider-button: "true"
  upstream: static://200
  reverse-proxy: "true"
  proxy-prefix: "/oauth2"
  set-xauthrequest: "true"
  email-domain: ""
  whitelist-domain: .nefcloud.top
  authenticated-emails-file: /etc/oauth2-proxy-config/allowed_emails.txt
# extraVolumes:
#   - name: config-volume
#     configMap:
#       name: admin-emails
# extraVolumeMounts:
#   - name: config-volume
#     mountPath: /etc/oauth2-proxy-config
#     readOnly: true
