apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
stringData:
    client_id: ENC[AES256_GCM,data:liHj5pz+OYoxMiM/N728Wyw=,iv:d7smUkDPArEHeP2Myhj7pyCpJjdA3U3hMuqJOuZrOss=,tag:pa0xqYKYzmAEX7Knxulb9w==,type:str]
    client_secret: ENC[AES256_GCM,data:SlYSgAReC6aWbhxdlZWK6s37doMb3L2GjxVIMI0GxSyN67APmr84VawW9LnDszGKdNFev7bkkcRkXoKnEZ4q,iv:rcEGGbdK0/fvy1xH7zrokuSq5guWeEg1TT+GY41hIbc=,tag:l0uyNmPii11Au3Ezylgxgg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1K0JjQ3ZieGlGN2RpTnlJ
            NFE2bWZuNVRYbDJyRWYwVE1LK3hNVm1qaGlVClhXaDMxS2lFaEJGcThIeVBEN1Q5
            SUVwbHh4UEpnNWh3Wk96clZabkpqejAKLS0tIFNDbDRGeVRMdUFPSGNSUEkwMkNu
            SERBeWs1MjRJZkFuYWVnYnBjbjVWOTAKK8/goHW8XICW6rx07LhtehR2YI7hOyT4
            +zbNl30FsGEUVgUw0XEH4o7at2ONXZSF17sNxAVLyxy5PF2U889PZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d8weq7fp7wct6sxvve94hap9v6jz6336txft64t5d5rx39vwwunq8nyjys
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-17T16:50:05Z"
    mac: ENC[AES256_GCM,data:fZm7dhhBkLccnZo3Wqqg7ar9UqQWEEhr5BRRJjGQOy48ZExavioBeArtlDto2JfHz/7Kj2HZ28+Tad8/N9/8b/u53hiRIvoeXm2wisNZ8XtyCD+X9CijJcwX0VJwROrQ8s2GcENzxuOfbFaWPA1PbxORjPjKx1nc+8Au/vzjGyQ=,iv:No/H8E4y70tmGF4UjCYEwCsB9u+uHNJ1v/m8qEegwjA=,tag:Ky7zRJMhlxU1rw6IU+Qv/Q==,type:str]
    version: 3.13.0
